eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

spring:
   cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**

    cloud:
      gateway:
        routes:
          - id: ORDER-SERVICE
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order/**



