#eureka:
#  instance:
#    prefer-Ip-Address: true
#    instance-id: ${spring.application.name}:${server.port}
#  client:
##        fetch-registry-with-eureka: true
##        register-with-eureka: true
#    service-url:
#      defaultZone: http://${HOST:eureka}:8761/eureka/

eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
  serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: PRODUCT-SERVICE

server:
  port: 8080
#  address: 10.0.61.123